install.packages("BiocManager")

BiocManager::install("ALL")
BiocManager::install("AnnotationDbi")
BiocManager::install("AnnotationFilter")
BiocManager::install("AnnotationHub")
BiocManager::install("BSgenome")
BiocManager::install("Biobase")
BiocManager::install("BiocFileCache")
BiocManager::install("BiocGenerics")
BiocManager::install("BiocParallel")
BiocManager::install("Biostrings")
BiocManager::install("DESeq2")
BiocManager::install("DelayedArray")
BiocManager::install("DiffBind")
BiocManager::install("EnrichmentBrowser")
BiocManager::install("EnsDb.Hsapiens.v86")
BiocManager::install("GO.db")
BiocManager::install("GenomeInfoDb")
BiocManager::install("GenomicFeatures")
BiocManager::install("GenomicRanges")
BiocManager::install("Gviz")
BiocManager::install("IRanges")
BiocManager::install("OrganismDbi")
install.packages("PoiClaClu", repos = "http://cran.us.r-project.org")
install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")
BiocManager::install("S4Vectors")
BiocManager::install("SummarizedExperiment")
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene")
BiocManager::install("TxDb.Mmusculus.UCSC.mm10.knownGene")
BiocManager::install("XVector")
BiocManager::install("airway")
install.packages("bindrcpp", repos = "http://cran.us.r-project.org")
install.packages("dbplyr", repos = "http://cran.us.r-project.org")
install.packages("dplyr", repos = "http://cran.us.r-project.org")
BiocManager::install("edgeR")
BiocManager::install("ensembldb")
BiocManager::install("genefilter")
install.packages("ggbeeswarm", repos = "http://cran.us.r-project.org")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
install.packages("graph", repos = "http://cran.us.r-project.org")
install.packages("hexbin", repos = "http://cran.us.r-project.org")
BiocManager::install("hgu95av2.db")
BiocManager::install("limma")
install.packages("matrixStats", repos = "http://cran.us.r-project.org")
install.packages("memoise", repos = "http://cran.us.r-project.org")
install.packages("mgcv", repos = "http://cran.us.r-project.org")
install.packages("nlme", repos = "http://cran.us.r-project.org")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("pathview")
install.packages("pheatmap", repos = "http://cran.us.r-project.org")
install.packages("readr", repos = "http://cran.us.r-project.org")
BiocManager::install("regioneR")
BiocManager::install("rtracklayer")
BiocManager::install("sva")
BiocManager::install("tximport")
BiocManager::install("tximportData")
BiocManager::install("vsn")